name: Verify changes

on: pull_request

jobs:
  verify:
    name: Verify changes
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 20
        uses: useblacksmith/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build types
        run: npm run types

      - name: Lint
        run: npm run lint

  web-tests:
    name: Web tests
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 20
        uses: useblacksmith/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build types
        run: npm run types

      - name: Install Playwright dependencies
        run: npx playwright install-deps && npx playwright install

      - name: Test
        run: npm run test:web

  node-tests:
    name: Node tests
    runs-on: blacksmith-4vcpu-ubuntu-2204
    strategy:
      matrix:
        node-version: ['18', '20']
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:node
